---
- name: Provisioning some openstack instances
  hosts: localhost
  vars:
    cloud: 1bfa-project
    servers:
      - name: server1
        image: rhel-8.3
        flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
        security_group: 1bfa-HostSG
        internal_network: 1bfa-dev-network
        keypair: 1bfa-keypair
        metadata: AnsibleGroup=osp_instances,deployment_name=dev
      - name: server2
        image: rhel-8.3
        flavor: GLOBAL-CPU_4_Memory_8192_Disk_30_flavor
        security_group: 1bfa-HostSG
        internal_network: 1bfa-dev-network
        keypair: 1bfa-keypair
        metadata: AnsibleGroup=osp_instances,deployment_name=dev
  
  tasks:
    - name: Create instances
      openstack.cloud.server: 
        cloud: "{{ cloud }}" 
        name: "{{ item.name }}" 
        image: "{{ item.image }}" 
        key_name: "{{ item.keypair }}" 
        flavor: "{{ item.flavor }}" 
        security_groups: "{{ item.security_group }}" 
        delete_fip: yes
        wait: no
        nics:
          - net-name: "{{ item.internal_network }}" 
        meta: "{{ item.metadata }}" 
        userdata: |
          #!/bin/bash
      loop: "{{ servers }}"
