- name: Setup backend
  hosts: backend
  vars:
    packages:
      - httpd
      - php
      - php-mysqlnd
    services:
      - httpd
    fw_ports:
      - 8080/tcp
  handlers:
    - name: restart_services
      service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ services }}"
  tasks:
    - name: Install firewalld
      yum:
        name: firewalld
        state: latest

    - name: Start firewalld
      service:
        name: firewalld
        enabled: yes
        state: started

    - name: Open fw ports
      firewalld:
        port: "{{ item }}"
        state: enabled
        immediate: true
        permanent: true
      loop: "{{ fw_ports }}"

    - name: Install packages
      yum:
        name: "{{ item }}"
      loop: "{{ packages }}"
    
    - name: enable selinux boolean
      seboolean:
        name: "{{ item }}"
        state: yes
        persistent: yes
      loop:
        - httpd_can_network_connect_db
        - httpd_can_network_connect

    - name: Configure httpd port
      replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen.*$'
        replace: 'Listen 8080'
      notify:
        - restart_services

    - name: Create apache image dir
      copy:
        src: images
        dest: /var/www/html/
      notify:
        - restart_services

    - name: Copy php index
      copy:
        src: index.php
        dest: /var/www/html/index.php
      notify:
        - restart_services

    - name: Start services
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ services }}"
      
